import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
// <a href="https://www.freepik.com/free-vector/elephant-logo-element-line-art-animal-illustration-vector_19598614.htm#query=elephant%20logo&position=3&from_view=keyword&track=robertav1_2_sidr">Image by rawpixel.com</a> on Freepik
export default function Home() {
  return (
    <>
      <Head>
        <title>Bunotan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Bunotan</h1>
        <Link href="/signup">Signup</Link>
        <Link href="/login">Login</Link>
        {/* <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div> */}
      </main>
    </>
  );
}
